name: chubster
description: A private-first nutrition journal

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.1.0
  equatable: ^1.0.0
  fancy_bottom_navigation: ^0.3.2
  font_awesome_flutter: ^8.5.0
  sqflite: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: PublicSans
      fonts:
        - asset: fonts/PublicSans-Thin.ttf
          weight: 100
        - asset: fonts/PublicSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/PublicSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/PublicSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/PublicSans-Light.ttf
          weight: 300
        - asset: fonts/PublicSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/PublicSans-Regular.ttf
          weight: 400
        - asset: fonts/PublicSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/PublicSans-Medium.ttf
          weight: 500
        - asset: fonts/PublicSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/PublicSans-SemiBold.ttf
          weight: 600
        - asset: fonts/PublicSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/PublicSans-Bold.ttf
          weight: 700
        - asset: fonts/PublicSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/PublicSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/PublicSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/PublicSans-Black.ttf
          weight: 900
        - asset: fonts/PublicSans-BlackItalic.ttf
          weight: 900
          style: italic
